version: "3.8"

services:
  api:
    build: .
    container_name: fastapi_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: whatsapp_api
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
